### ISSUE TITLE
Cannot unpack .rar files

### ISSUE THREAD

**Issue by Wolfmyths** [Wolfmyths/Myth-Mod-Manager#12]
I'm not sure if this is possible to fix because of the owners of winrar and you need to own it to open them.

**Comment by Shady2kOver** [comment]
Hi, if youre still having this issue , you can use python's patool library to unpack the rar files

```
import patoolib
patoolib.extract_archive("foo_bar.rar", outdir="path here")

```

**Comment by Wolfmyths** [comment]
> Hi, if youre still having this issue , you can use python's patool library to unpack the rar files

This worked! Thank you so much!
