### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by Wolfmyths** [Wolfmyths/Myth-Mod-Manager#18]
Python and PySide6 make it easy to create cross-platform applications, but there are a couple of things preventing the program to work on Linux.

- [x] Replace or use a alternative to os module's `os.startFile()`
- [x] Assume certain environments like `%AppData%` where the user's crash logs are located
- [x] Create a Github workflow to build a MacOS/Linux version
- [x] Replace .bat files with shell

If anything else I find is platform-dependent I will add it to the list

**Comment by Sprixitite** [comment]
Hey, daily Linux user here, I don't really have much of a use for a mod manager, but I've definitely seen a good few Linux users who do and I wanted to try help out on this, I've submitted #24 to fix the use of os.startFile, I'm not too familiar with the python ecosystem, and I'm not familiar with batch files or github actions, so I don't think I can fix the batch files/workflow issues, but I'll look into the matter of the file path, as figuring out where it is on linux will be a bit of an issue

**Comment by Sprixitite** [comment]
The steam data folder seems to be ~/.steam/steam/ on linux nowadays, if running under proton the executable should be payday2_win32_release.exe as it is on windows, I don't know what the name of the linux native executable is

Crashlogs will also be stored in different places depending on if proton is being used (I've no idea where linux native puts it's crashlogs, assuming it has any), I imagine you'd have to use some steam API to detect if proton is being used

Also having taken a bit more of a look at how you're launching the executable with the .bat file I think I might be able to make a shell script to do the equivalent on linux

**Comment by Wolfmyths** [comment]
>I imagine you'd have to use some steam API to detect if proton is being used

As of more recent PAYDAY 2 versions, native Linux support has been discontinued.

https://store.steampowered.com/news/app/218620/view/3665414601842198623?l=english

I don't think we should be in-charge of detecting if proton is being used or not.

> Crashlogs will also be stored in different places depending on if proton is being used

Does proton use .exe? I thought proton was just a big handshake for emulating windows calls. I'm surprised it has it's own environment like that if that's the case.

**Comment by Sprixitite** [comment]
Several people still run the native Linux build, it'd be incredibly unfortunate to drop support especially when it's only 2-3 updates off of the windows build 

Proton has a similar executable path but stores the crashlogs in a wine prefix in steamapps/compatdata/218620 at the same place windows usually places the crashlogs

I don't know where Linux native stores the crashlogs

**Comment by Wolfmyths** [comment]
> it'd be incredibly unfortunate to drop support especially when it's only 2-3 updates off of the windows build

I didn't know running games Linux natively when proton exists was so important to people. I'll keep it in mind then when we're making this.

Thanks for informing me on the Linux dirs.

If you do want to try and add in your own shell scripts you can build the program on your own machine and test it out for yourself. Most of the program should work if it launches correctly. Errors should only raise from the mentioned issues above.
