### ISSUE TITLE
Disabling mods removes them entirely

### ISSUE THREAD

**Issue by Jian-Ng** [Wolfmyths/Myth-Mod-Manager#25]
I was using the old version for a while before updating, I noticed that disabling mods no longer moves the mod folder to the "disabled-mods" folder, but rather the contents of the mod folder instead. I downloaded the mod from the releases page.

I have a few screenshots and a video attached. My software doesn't record the right-click somehow, but look to the right and you can see that the mod is disabled.

https://github.com/Wolfmyths/Myth-Mod-Manager/assets/110548158/e855a66b-e436-4f1b-a652-17c90762c882

![Screenshot 2023-09-01 223759](https://github.com/Wolfmyths/Myth-Mod-Manager/assets/110548158/cc84a956-52c8-4514-bf83-86b5aa53edb6)
![Screenshot 2023-09-01 223831](https://github.com/Wolfmyths/Myth-Mod-Manager/assets/110548158/453d7b3d-ca1b-49fb-a409-c80308231341)

**Comment by Wolfmyths** [comment]
Thanks for giving me a informative bug report.

I'm so sorry this has happened here's an easy way to revert this if you don't have a backup of your mods:

+ Make a new folder in the disabled mods folder and rename it to the mod you want properly disabled
    - Go to `mods.ini` and find the mod that was disabled incorrectly to get the exact name if you can't remember the mod name
+ Move the correct contents of the mod into the newly created folder

If this has happened to more than one mod, reinstalling them works but remember to delete the incorrect files in the disabled mods directory

I will work on this as soon as I can.

**Comment by Wolfmyths** [comment]
This issue will be fixed and a patch will be released later today.

The issue was that the destination path for moving a mod to the disabled mods directory was not including the mod folder itself.

Before:
```py
self.move(disabledModsPath, modDestPath)
```


After:
```py
self.move(os.path.join(disabledModsPath, mod), modDestPath)
```

Thanks for reporting this bug it really means a lot.
