### ISSUE TITLE
Linux - Error: Game Path is not valid

### ISSUE THREAD

**Issue by LegitGreenBoi** [Wolfmyths/Myth-Mod-Manager#50]
Running on EndeavourOS/Arch Linux, I get an error when entering the game path.

The path is correct but it isn't being accepted by the program.

**Comment by Wolfmyths** [comment]
Is it when you go to the settings tab to change the path?

If so, this is a bug specifically on Linux sorry about that. It is already patched in the newest update which should be released soon.

I think if you manually input the file location in `config.ini` it should work

**Comment by LegitGreenBoi** [comment]
It's right at the first startup

The config.ini is empty but if I try to paste it in anyway, it spits out errors and doesn't launch at all.

**Comment by Wolfmyths** [comment]
Oh wow I'll take a look, sorry about that

Try copy/pasting this into config.ini and customize it to your liking and see if you can get past it (This is my config file)
```
[OPTIONS]
game_path = D:/SteamLibrary/steamapps/common/PAYDAY 2
mmm_update_alert = True
color_theme = dark
windowsize_w = 1143
windowsize_h = 800
```

**Comment by LegitGreenBoi** [comment]
Hmm. For some reason pasting and editing your config with my path still doesn't seem to work.

When I open it, all the other settings apply but it still prompts me for a path and won't accept it.

**Comment by Wolfmyths** [comment]
I know this might sound a little silly, but I just came to realization that there's a change the program might be allowing escape characters through.

Try replacing `/` with `\\` in the ini file

**Comment by Wolfmyths** [comment]
I removed the requirement for detecting the executable for payday 2 in the newest patch which is out right now

If there are any other issues let me know

**Comment by LegitGreenBoi** [comment]
Ok, I updated and now it sees all my mods/mods_overrides without having to change anything. Thanks!
